USE ecuaciones;
ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_USER FOREIGN KEY FK_ANSWER_USER (idUser) REFERENCES user(idUser) ON UPDATE CASCADE ON DELETE CASCADE ;

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY FK_ANSWER_QUESTION (idQuestion) REFERENCES question(idQuestion) ON UPDATE CASCADE ON DELETE CASCADE ;